config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews, except: :new
  resources :requests, except: :new
  resources :turns
  # get 'home/index'
  get 'home/about'
  root 'home#index'

  get 'requests/:turn_id/new', to: 'requests#new', as: 'new_request'
  get 'requests/:request_id/accept', to: 'requests#accept', as: 'accept_request'
  get 'requests/:request_id/refuse', to: 'requests#refuse', as: 'refuse_request'
  get 'reviews/:user_id/new', to: 'reviews#new', as: 'new_review'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :turn
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :user
  has_many :requests
  has_many :users_requests, through: :requets, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :turns
         has_many :reviews
         has_many :requests
         has_many :turns_requests, through: :requests, source: :turn
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
    @turn = Turn.find(params[:turn_id])
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(description: request_params[:description], status: "Not Accepted Yet", user_id: current_user.id, turn_id: request_params[:turn_id])

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def accept
    request = Request.find(params[:request_id])
    request.status = "Accepted"
    request.save
    redirect_to requests_url
  end

  def refuse
    request = Request.find(params[:request_id])
    request.status = "Not Accepted"
    request.save
    redirect_to requests_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:description, :turn_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @user = User.find(params[:user_id])
    @review = @user.reviews.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    user = User.find(review_params[:user_id])
    @review = user.reviews.new(rating: review_params[:rating], content: review_params[:content])

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :content, :user_id)
    end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: %i[ show edit update destroy ]

  # GET /turns or /turns.json
  def index
    @turns = Turn.all
  end

  # GET /turns/1 or /turns/1.json
  def show
    @passengers = []
    turn = Turn.find(params[:id])
    turn.requests.each do |request|
      if request.status == "Accepted"
        @passengers.push(request.user.email)
      end
    end
  end

  # GET /turns/new
  def new
    # @turn = Turn.new
    @turn = current_user.turns.new
  end

  # GET /turns/1/edit
  def edit
  end

  # POST /turns or /turns.json
  def create
    # @turn = Turn.new(turn_params)
    @turn = current_user.turns.new(turn_params)

    respond_to do |format|
      if @turn.save
        format.html { redirect_to turn_url(@turn), notice: "Turn was successfully created." }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1 or /turns/1.json
  def update
    respond_to do |format|
      if @turn.update(turn_params)
        format.html { redirect_to turn_url(@turn), notice: "Turn was successfully updated." }
        format.json { render :show, status: :ok, location: @turn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turns/1 or /turns/1.json
  def destroy
    @turn.destroy

    respond_to do |format|
      format.html { redirect_to turns_url, notice: "Turn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turn_params
      params.require(:turn).permit(:weekday, :departure_address, :departure_time, :turn_type, :people_limit, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/home/_header.html.erb
<%= link_to 'Movingly App', root_path %>
<%= link_to 'About us', home_about_path %>
<%= link_to 'Turns', turns_path %>

<% if user_signed_in? %>
  <%= link_to 'Requests', requests_path %>
  <%= link_to 'Reviews', reviews_path %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <%= link_to 'Edit Profile', edit_user_registration_path %>

<% else %>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <%= link_to 'Sign In', new_user_session_path %>
<% end %>

app/views/home/about.html.erb
<h1>About Movingly</h1>

app/views/home/index.html.erb
<h1>Welcome to Movingly! 🎉</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movingly App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>

    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <% if @turn %>
    <div class="field">
      <%= form.number_field :turn_id, value:@turn.id, type: :hidden %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>

      <% if request.user == current_user %>
        <tr>
          <td><%= request.description %></td>
          <td><%= request.status %></td>
          <td><%= link_to 'Edit', edit_request_path(request) %></td>
          <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

      <% elsif current_user.turns.include? request.turn %>
        <tr>
          <td><%= request.description %></td>
          <td><%= request.status %></td>
          <td><%= link_to 'Accept', accept_request_path(request) %></td>
          <td><%= link_to 'Refuse', refuse_request_path(request) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', turns_path %>

app/views/requests/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <% if @user %>
    <div class="field">
      <%= form.number_field :user_id, value:@user.id, type: :hidden %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.reviews.each do |review| %>
      <tr>
        <td><%= '⭐️' * review.rating %></td>
        <td><%= review.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', turns_path %>

app/views/reviews/show.html.erb
<p>
  <strong>Rating:</strong>
  <%= '⭐️' * @review.rating %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', turns_path %>

app/views/turns/_form.html.erb
<%= form_with(model: turn, local: true) do |form| %>
  <% if turn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turn.errors.count, "error") %> prohibited this turn from being saved:</h2>

      <ul>
        <% turn.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weekday %>
    <%= form.text_field :weekday %>
  </div>

  <div class="field">
    <%= form.label :departure_address %>
    <%= form.text_field :departure_address %>
  </div>

  <div class="field">
    <%= form.label :departure_time %>
    <%= form.time_select :departure_time %>
  </div>

  <div class="field">
    <%= form.label :turn_type %>
    <%= form.text_field :turn_type %>
  </div>

  <div class="field">
    <%= form.label :people_limit %>
    <%= form.number_field :people_limit %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turns/edit.html.erb
<h1>Editing Turn</h1>

<%= render 'form', turn: @turn %>

<%= link_to 'Show', @turn %> |
<%= link_to 'Back', turns_path %>

app/views/turns/index.html.erb
<h1>Turns</h1>

<table>
  <thead>
    <tr>
      <th>Weekday</th>
      <th>Departure address</th>
      <th>Departure time</th>
      <th>Turn type</th>
      <th>People limit</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turns.each do |turn| %>
      <tr>
        <td><%= turn.weekday %></td>
        <td><%= turn.departure_address %></td>
        <td><%= turn.departure_time.to_s(:time) %></td>
        <td><%= turn.turn_type %></td>
        <td><%= turn.people_limit %></td>
        <td><%= turn.address %></td>
        <td><%= link_to 'Show', turn %></td>
        
        <% if current_user == turn.user %>
          <td><%= link_to 'Edit', edit_turn_path(turn) %></td>
          <td><%= link_to 'Destroy', turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Turn', new_turn_path %>
<% else %>
  <%= link_to 'New Turn', new_user_session_path %>
<% end %>

app/views/turns/new.html.erb
<h1>New Turn</h1>

<%= render 'form', turn: @turn %>

<%= link_to 'Back', turns_path %>

app/views/turns/show.html.erb
<p>
  <strong>Weekday:</strong>
  <%= @turn.weekday %>
</p>

<p>
  <strong>Departure address:</strong>
  <%= @turn.departure_address %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @turn.departure_time.to_s(:time) %>
</p>

<p>
  <strong>Turn type:</strong>
  <%= @turn.turn_type %>
</p>

<p>
  <strong>People limit:</strong>
  <%= @turn.people_limit %>
</p>

<p>
  <strong>Address:</strong>
  <%= @turn.address %>
</p>

<p>
  <strong>Driver:</strong>

  <% if current_user != @turn.user and user_signed_in? %>
    <%= link_to @turn.user.email, new_review_path(@turn.user) %>
  <% elsif current_user != @turn.user and not user_signed_in? %>
    <%= link_to @turn.user.email, new_user_session_path %>
  <% else %>
    <%= @turn.user.email %>
  <% end %>
</p>

<p>
  <strong>Passengers:</strong>
  <%= @passengers.join(', ') %>
</p>

<% if current_user == @turn.user %>
  <%= link_to 'Edit', edit_turn_path(@turn) %> |
<% elsif user_signed_in? %>
  <%= link_to 'Send Request', new_request_path(@turn) %> |
<% else %>
  <%= link_to 'Send Request', new_user_session_path %> |
<% end %>

<%= link_to 'Back', turns_path %>